### PR TITLE
Fun/release 3.4

### PR DESCRIPTION
**Pull request by rmoch**
J'ai mergé dans cette branche les PR en attente pour deploiement/recette sur Cargo

### CODE REVIEW

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Comment by regisb** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Pull request merged**
