### PR TITLE
pep8

### PR DESCRIPTION
**Pull request by rmoch**

### CODE REVIEW

**Comment by regisb** [comment]
C'est presque parfait : http://ci.alt.openfun.fr/job/fun-apps/1405/violations/

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
jenkins test this please

**Comment by rmoch** [comment]
Jenkins test this please.

**Comment by regisb** [comment]
Jenkins test this please.

**Comment by regisb** [comment]
Jenkins test this please.

**Comment by regisb** [comment]
test this please.

**Comment by regisb** [comment]
test this please.

**Pull request closed without merging**
