### PR TITLE
Fixes bug on unsorted courses in the rss feed.

### PR DESCRIPTION
**Pull request by jpaille**
This commit closes issue #1459.

Also :
-> Refactors and adds tests for CoursesFeed.
-> Removes empty course_list.py file.

### CODE REVIEW

**Comment by regisb** [comment]
Can one of the admins verify this patch?

**Comment by jpaille** [comment]
test this please

**Comment by regisb** [comment]
test this please

**Comment by regisb** [comment]
test this please

**Comment by regisb** [comment]
test this please

**Comment by regisb** [comment]
Great fix. lgtm.

**Comment by jpaille** [comment]
jenkins test this please

**Comment by jpaille** [comment]
test this please !

**Pull request closed without merging**
