### PR TITLE
Fix missing stats in problem stats csv report

### PR DESCRIPTION
**Pull request by regisb**
The missing stats were caused by superusers. Superusers were removed
from the stats because some of them did not have an associated user
profile. Here, we incorporate stats from superusers and skip the profile
information in the report if the data is missing.

This closes issue #2393.

### CODE REVIEW

**Comment by regisb** [comment]
Jenkins test this please.

**Comment by regisb** [comment]
Jenkins test this please.

**Comment by lazybird** [comment]
Looks good.

**Comment by rmoch** [comment]
lgtm

**Pull request closed without merging**
