### PR TITLE
Ordering course subjects by score and then by name

### PR DESCRIPTION
**Pull request by lazybird**
In addition to ordering by score, we want to order course subjects alphabetically.

### CODE REVIEW

**Comment by regisb** [comment]
1) In commit message replace "the" by "and"
2) Add a tiny unit test?

Otherwise, lgtm.

**Comment by lazybird** [comment]
Fixed commit message. I'm not sure why the compilation fails, but that's happening elsewhere.

**Comment by regisb** [comment]
Jenkins, test this please.

**Comment by regisb** [comment]
Jenkins, test this please.

**Pull request closed without merging**
